services:
  streamdeckbuddy.api:
    image: streamdeckbuddy.api
    build:
      context: .
      dockerfile: StreamDeckBuddy.API/Dockerfile
    ports:
      - "5199:8080"
    volumes:
      - C:\Users\gutor\AppData\Roaming\Elgato\StreamDeck\IconPacks:/streamdeckicons
      - C:\tmp\StreamDeckBuddy:/data